name: push-warren-image

on:
  push:
    branches: [ main ]
    paths:
      - 'images/warren/**'
      - '.github/workflows/push-warren-image.yml'
      - '.github/workflows/build-and-push-image.yml'

jobs:
  build:
    uses: ./.github/workflows/build-and-push-image.yml
    with:
      image_name: warren
      image_path: images/warren
    secrets: inherit