name: terraform-apply-mztn-service

on:
  push:
    branches: [ main ]
    paths:
      - 'google-cloud/mztn-service/**'
      - '.github/workflows/terraform-apply-mztn-service.yml'

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    uses: ./.github/workflows/terraform-apply.yml
    with:
      working_directory: google-cloud/mztn-service
      project_id: mztn-service
    secrets: inherit
